### ISSUE TITLE
How to run new migrations against tenant schemas?

### ISSUE THREAD

**Issue by iancanderson** [Dania02525/apartmentex#11]
Here is the situation:
- Tenants sign up: `Apartmentex.new_tenant(Repo, tenant)`
- Developer adds new migration file in `priv/repo/tenant_migrations/`
- Need to run migrations for all tenants

Maybe it makes sense to have an `Apartmentex.migrate_tenantsI(Repo, tenants)` function that would migrate each tenant forward.

Or maybe this should be a mix task?
`mix apartmentex.migrate TenantModel`
Note the `TenantModel` parameter, since apartmentex would have to query for all tenants to calculate the schema prefixes that it needs to migrate. Or I suppose maybe apartmentex could query the database for a list of all schema that start with the prefix?

How to deal with failure? What if a migration fails for one tenant and not others?

Sorry - lots of thinking out loud here 😄

**Comment by iancanderson** [comment]
Here is how the `apartment` gem handles the list of schema names: https://github.com/influitive/apartment/blob/57805b2fe910b2ccc56b667fb94f8469be1b74ed/README.md#managing-migrations

**Comment by Dania02525** [comment]
The idea of migrate_tenant/2 is good, but for migrating a whole set of tenants I think it makes more sense in a mix task (maybe in addition to a function?).  As for catching failures, each tenants schema (or db in mysql) already gets a schema migrations table, meaning we really just need to catch and report on failure of the transaction for that tenant's schema.  

I'll work on a mix task to do this for the older versions of ecto, and we can make whatever changes needed to get it going with 2.0- looks like it will need to do something with the sandbox- reference: https://github.com/elixir-ecto/ecto/blob/master/lib/mix/tasks/ecto.migrate.ex

Do you think it would be worthwhile having a table on the public schema to indicate which migration each tenant has proceeded to? maybe a column on the tenant table?

Edit: Here's my WIP branch- trying to determine how to write a test where the task needs to pull tenants from the database- I think I'll need to pull this test out of the transaction and commit/clean up the test db. https://github.com/Dania02525/apartmentex/tree/mix_task_for_tenant_migrations

**Comment by iancanderson** [comment]
> The idea of migrate_tenant/2 is good, but for migrating a whole set of tenants I think it makes more sense in a mix task (maybe in addition to a function?).

Agreed, I think a mix task makes the most sense.

> Do you think it would be worthwhile having a table on the public schema to indicate which migration each tenant has proceeded to? maybe a column on the tenant table?

Did you have a specific use case in mind for that table? Maybe to support a `mix apartmentex.migrate.status` task, that could print out the most recent migration run on each tenant, and return an error code if some of the tenants don't have the most recent migration applied?

RE the WIP branch, you might already have this as a plan, but it would be nice to keep the library agnostic from the name of the "tenants" table (the app I'm working on uses a different table name for the tenants).

Here's the line I'm talking about:

``` elixir
tenants = repo.all(from t in "tenants", select: t.id)
```

Maybe it makes sense to have another apartmentex configuration option for the table name? Or maybe be able to specify the model module?

**Comment by Dania02525** [comment]
> Did you have a specific use case in mind for that table? Maybe to support a mix apartmentex.migrate.status task, that could print out the most recent migration run on each tenant, and return an error code if some of the tenants don't have the most recent migration applied?

I was just thinking it might be easier from a management perspective- an admin could simply query to the public schema for migrations < xxx, rather than having to dig into each schema and look at its respective schema_migrations table.  

I like the idea of keeping what were calling the tenant module agnostic are you thinking we'd pass it in with the config?

**Comment by iancanderson** [comment]
RE putting migration info in the public schema - I like the idea of the
convenience for querying the tenant migration statuses from a single table,
but I would worry that it could get out of date with the schema_migrations
tables within the private schemas. Maybe there's a good way to make sure
that doesn't happen?

Currently, the library works without assuming the table name or module name
of the tenant model. It would be nice to keep it that way if possible. If
the library does need to know the module of the tenant model for some
reason, then yea, it probably makes sense to set that as a configuration
option.

Are you thinking you'd need the module to query the tenants so the mix task
can migrate them all? Something else to consider is letting the user
provide a module that has a "tenants" function that returns structs that
have an id value. That way, the tenants could be hardcoded, or loaded from
a file, or loaded from a database, based on what the user of the library
wants to do. Maybe that's more flexible than we need though? FWIW, letting
apartmentex query for tenants by providing the model module would work for
my current use case.

## 

Ian Anderson
Sent with Airmail

**Comment by Dania02525** [comment]
To your last point- I was considering allowing a query to be passed to the mix task, something like `mix apartmentex.migrate_all -q 'from t in Tenant, where ....., select t' to prevent users having to commit code to modify which tenants they can migrate from the command line.  I really like your idea too since we'd be able to run some script to get them- I should be able to parse the query option as well as the script option in the mix task to allow for either.  that removes the need to know the table module name beforehand and gets us back to being table name agnostic for tenants :-)
