### ISSUE TITLE
Having trouble with install

### ISSUE THREAD

**Issue by snewcomer** [Dania02525/apartmentex#18]
Any thoughts on what I am missing?

![screen shot 2016-08-21 at 12 44 32 pm](https://cloud.githubusercontent.com/assets/7374640/17839448/11543c94-679d-11e6-82be-8cc3e8ee7642.png)

https://github.com/Dania02525/apartmentex/blob/master/lib/apartmentex.ex#L6

**Comment by Dania02525** [comment]
Looks like def delegate is no longer taking default parameters. Ill get a fix up Monday for you, which version of elixir are you using?

**Comment by snewcomer** [comment]
Thanks!  1.2.4.  Then upgraded to 1.3.2 and it worked.  My bad.

**Comment by Dania02525** [comment]
Awesome, glad you got it working.  I'll investigate this and ensure I specify minimum elixir version needed so this can be avoided in the future.

**Comment by Rovel** [comment]
Hey @Dania02525 I'm having a lookalike issue when compiling the deps for elixir 1.5.1 and phx 1.3 could that be the same?
