### ISSUE TITLE
Prefix in `Apartmentex.drop_tenant` not being escaped properly?

### ISSUE THREAD

**Issue by brandonparsons** [Dania02525/apartmentex#27]
I'm trying to get `apartmentex` working for me. I'm assuming I'm not doing anything too crazy :)

I'm using "slugs" as the tenant identifier on my Postgres schemas (I'm not using integer IDs, so would end up using a UUID, or a slug).  So for example, my database schemas look like `tenant_a-test-person`.

Adding a tenant is working just fine. For example:

``` elixir
Apartmentex.new_tenant(Repo, client.slug)
# --> Apartmentex.new_tenant(Repo, "a-test-person")
```

However, when I go to drop the schema, I'm getting errors due to the presence of `-` in the schema name.  For example:

``` elixir
Apartmentex.drop_tenant(Repo, client.slug)
# --> Apartmentex.drop_tenant(Repo, "a-test-person")
```

This ends up calling `DROP SCHEMA tenant_test-person CASCADE []` in the DB, and throws an error, as per below:

```
[debug] QUERY ERROR db=0.5ms
DROP SCHEMA tenant_test-person CASCADE []
[debug] QUERY OK db=0.2ms
rollback []
{:error, :drop_schema,
 %Postgrex.Error{connection_id: 70573, message: nil,
  postgres: %{code: :syntax_error, file: "scan.l", line: "1053",
    message: "syntax error at or near \"-\"", pg_code: "42601", position: "24",
    routine: "scanner_yyerror", severity: "ERROR"}}, %{}}
```

I think all that needs to happen here is surround the schema name in quotes, e.g. `DROP SCHEMA "tenant_test-person" CASCADE []` - at least it worked for me testing in a PG shell.

Is there a way to accomplish this with the library as-is?  I don't think using UUIDs (instead of a slug) would make any difference here, as they also include `-` characters.

Thanks for your help and putting this library together!

**Comment by mhussa** [comment]
there's a pull request which fixes this apparently, haven't tried it just pointing it out :)

https://github.com/Dania02525/apartmentex/pull/25

**Comment by Dania02525** [comment]
@brandonparsons The PR referenced by @mhussa has been merged and published to hex- please change your deps entry to -> 0.2.2.  Let me know if this issue resolves for you.  Thanks!

**Comment by brandonparsons** [comment]
@Dania02525 Whoo hoo! Yep it works. I obviously didn't know you guys were already all over this :)

Again, thanks for putting this library together. I'm just getting into Elixir/Phoenix, and wondering about converting a reasonably young Rails app over. If this library didn't exist, it wouldn't even be an option for me :) Will see if I can get up to speed fast enough!

**Comment by BenMorganIO** [comment]
@brandonparsons as of Ecto 2 you thankfully don't actually need this library. However, the added sugar that Apartmentex supplies is very nice and saves you from learning too much advanced Ecto before one's ready.
