### ISSUE TITLE
** (Postgrex.Error) ERROR (undefined_table): relation "locations" does not exist

### ISSUE THREAD

**Issue by brandonparsons** [Dania02525/apartmentex#28]
Hi there,

I'm trying to define my first "model" for a table that exists within each tenant's PG schema (i.e. it is created via a migration in `priv/repo/tenant_migrations`.

I define the Ecto schema as per normal:

``` elixir
  schema "locations" do
    field :address
    # ......

    timestamps()
  end
```

But it appears that Ecto can't find the table:

```
     ** (Postgrex.Error) ERROR (undefined_table): relation "locations" does not exist
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:463: Ecto.Adapters.SQL.struct/6
       (ecto) lib/ecto/repo/schema.ex:397: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:193: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:124: Ecto.Repo.Schema.insert!/4
       test/myapp/locations/location_test.exs:24: (test)
```

The `locations` table does **not** exist in my public schema, but it does inside each tenant's schema.

Am I missing something?

I am using `ecto 2.X`, `postgrex ~> 0.12.1` and `apartmentex ~> 0.2.2`.

**Comment by brandonparsons** [comment]
Closing because I'm pretty sure I did something dumb.

**Comment by brandonparsons** [comment]
Nope, still having an issue (I was doing something dumb earlier though).  The error should have shown as follows:

```
     ** (Postgrex.Error) ERROR (undefined_table): relation "tenant_another-operator.locations" does not exist
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:463: Ecto.Adapters.SQL.struct/6
       (ecto) lib/ecto/repo/schema.ex:397: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:193: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:124: Ecto.Repo.Schema.insert!/4
       test/myapp/locations/location_test.exs:24: (test)
```

Note the quoting of the table name (`"tenant_another-operator.locations"`). It would work if the schema name was quoted (e.g. `"tenant_another-operator"."locations"`)

**Comment by brandonparsons** [comment]
:(

Sorry! I got it!

**Comment by BenMorganIO** [comment]
@brandonparsons happy you figured it out!

**Comment by natewallis** [comment]
Please tell me what dumb thing you did, because it turns out that I am dumb too!
