### ISSUE TITLE
Ecto 2.1 compatibility issues

### ISSUE THREAD

**Issue by freiden** [Dania02525/apartmentex#34]
It seems like the last version of Ecto and Apartmentex have some issues.
On my application migrations don't work anymore.
I tried to run all the library tests with Ecto 2.1, there some [broken tests](https://github.com/Dania02525/apartmentex/pull/35/files) but it's related to the errors messages returns by Postgresql.

Did you try to use it met some problems when running the library with Ecto 2.1 in a real project?

**Comment by freiden** [comment]
Am I the only one to have this problem?

**Comment by BenMorganIO** [comment]
Probably not. We gotta wait for @Dania02525 to review :)

**Comment by hopewise** [comment]
I also have this issue when `mix deps.get`:

```
Failed to use "ecto" (version 2.1.3) because
  apartmentex (version 0.2.2) requires ~> 2.0.2
  phoenix_ecto (version 3.2.1) requires ~> 2.1
  mix.lock specifies 2.1.3
```

Is there an alternative to use while @Dania02525 check this issue?

**Comment by freiden** [comment]
@hopewise The only way I found was to lock the version. Unfortunately there not enough tests on the library to ensure that changing a behavior for an adapter will not impact an other.
I started on replicating the Postgresql tests added by @iancanderson but didn't had enough to pursue it.

**Comment by Dania02525** [comment]
seems to have been addressed in https://github.com/Dania02525/apartmentex/pull/35

closing.  Thank you!

**Comment by freiden** [comment]
Hi @Dania02525 issue #35 don't fix this problem unfortunately. It fixed errors in the tests but it doesn't change that on my applications the creation of tenant doesn't work anymore.
Library tests aren't enough to reproduce the problem.
