### ISSUE TITLE
Customise migration folder

### ISSUE THREAD

**Issue by opsb** [Dania02525/apartmentex#36]
Currently you can use the `priv` option on the repo to change the path used for the migrations e.g.

`priv: "mydir"`

will mean the migrations are stored in

`priv/mydir/tenant_migrations`.

I'm building an API where the tenants are referred to as `services` and I'd like the migrations directory to line up with that e.g.

`priv/repo/service_migrations`

How would you feel about making the `priv` option specify the whole path instead of just the part before `tenant_migrations`?

e.g.

`priv: "repo/service_migrations"`

means the migrations are stored in

`priv/repo/service_migrations`

**Comment by Dania02525** [comment]
Added a config option to specify migration path, :migrations_folder here: https://github.com/Dania02525/apartmentex/commit/67f27361c86d1d2d7e1dd7e202a0acd820c025ff

Please remove from your mix lock and clean/get apartmentex :-)
