### ISSUE TITLE
How to use prefix for schema's name in the project

### ISSUE THREAD

**Issue by stenionobres** [Dania02525/apartmentex#37]
Hello,

I'm make some tests with the apartmentex and I have a doubt.

I'm try to use a prefix configuration for a schema name e for one reason do not works very well, always the application use the default prefix `"tenant_"`.

My project is a umbrella project and inside a config.exs of the projects that's have a Ecto dependence I put:

`config :apartmentex, schema_prefix: "client_"`

Unfortanely do not work. I did a search and I found out that the

https://groups.google.com/forum/#!msg/elixir-lang-talk/5yX9hBNEXe0/7UYWeTKmjaYJ

Using the strategy of the previous post the configuration works: 
`config :tenant_prefix, :apartmentex, %{ schema_prefix: "client_" }`

However I need change the call in apartmentex for: 
`Application.get_env(:tenant_prefix, :apartmentex).schema_prefix`

A another way is change the "key" `:apartmentex` for the my application name. Ex:

`config :my_app, schema_prefix: "client_"`

And change the call in apartmentex for 
`Application.get_env(:my_app, :schema_prefix)`

How should I proceed?

Sorry for english mistakes.

PS: I'm using Ecto 3.0. When the compatibility will be available in Hex?

**Comment by Dania02525** [comment]
I'm sorry, I'm not terribly familiar with umbrella applications, is there a top level application or supervisor? if apartmentex is in the running applications of the mixfile for :my_app, you should be able to access its config from any app running underneath of it:

```elixir
def application do
  [aplications: [:ecto, :apartmentex]
end
```
and in the top level /config, just config apartmentex normally.  I think you may run into an issue if apartmentex is only running on some lower supervised application where it won't show up in :my_app applications.

**Comment by Dania02525** [comment]
This should be fixed by https://github.com/Dania02525/apartmentex/pull/48
