### ISSUE TITLE
pool size?

### ISSUE THREAD

**Issue by hopewise** [Dania02525/apartmentex#41]
I was asking about pool_size setting in config here: 
https://elixirforum.com/t/ecto-pool-size/4120, Do you have any recommendation?

Thanks

**Comment by Dania02525** [comment]
It will depend on your server hardware- I think default production setting in ecto is 20, but with a powerful server- something larger than ec2 medium instance, you could move that size up.  the db pool size is rarely the limiting factor in application code unless a ton of concurrent users are all writing to the db, in which case you will need a powerful server anyway.

**Comment by hopewise** [comment]
yep, thank you
