### ISSUE TITLE
New Patch Release?

### ISSUE THREAD

**Issue by tomciopp** [Dania02525/apartmentex#42]
I would like to use Apartmentex in an application but it looks like the current version posted to hex does not support the most recent versions of Ecto and Postgrex. However, it looks like there are commits in master that support the newer versions of these libs. Is there anything holding back a new patch release? If so, I would be glad to help out since I would rather not have to reinvent the wheel on my side.

**Comment by Dania02525** [comment]
👍 will get this up on hex this week

**Comment by Dania02525** [comment]
Version 2.3 is now on hex pm
