### ISSUE TITLE
Broken deps as Ecto was upgraded

### ISSUE THREAD

**Issue by Rovel** [Dania02525/apartmentex#46]
Hi, 

As Ecto was updated the module Apartmentex.MigrationsPathBuilder no longer works since `build_repo_priv/1` was removed/rename/made private from the project:
```
defmodule Apartmentex.MigrationsPathBuilder do
  import Mix.Ecto, only: [build_repo_priv: 1]
  @migrations_folder Application.get_env(:apartmentex, :migrations_folder) || "tenant_migrations"

  def tenant_migrations_path(repo) do
    Path.join(build_repo_priv(repo), @migrations_folder)
  end
end
```
Any clue of the new method/fix for this?

Reference at:
https://github.com/elixir-ecto/ecto/issues/2278

**Comment by timmhirsens** [comment]
@Rovel how did you fix this for you?

**Comment by Rovel** [comment]
Hey @fr1zle 
Actually the hex package / github is fixed but for some weird reason since there is no version change its doesn't upgrade, even when you tells it too. (mix deps.get or upgrade) so there is 2 options:
1. Get the code from github and update your apartmetex lib inside the project via code editor, since this is a small lib its easy, next time you make mix deps.get it will update properly
2. Point the dep to the github repo, so you will be in sync with the latest commits from this repo

I went with the first one, but I think the second is more suitable.

**Comment by timmhirsens** [comment]
@Rovel: Thanks for the super detailed answer! Totally forgot about the option 2!

Still would be great if the version in hex could be updated.

**Comment by Dania02525** [comment]
Whoops, ill get this updated tomorrow.  Thank you for mentioning it!
