### ISSUE TITLE
Unable to run tenant_migrations on production remote_console

### ISSUE THREAD

**Issue by lulu-2021** [Dania02525/apartmentex#50]
Hi there at the moment am unable to create a new tenant (run the migrations on the new tenant) on a production deployment. It is complaining about Mix which isn't normally present in production - any ideas what I am doing wrong - am using Edeliver/distillery to do the release/deploy
Thanks

Error on the remote_console on the prod instance

iex(present_me@127.0.0.1)5> Apartmentex.new_tenant(Repo, foo.id)
** (UndefinedFunctionError) function Mix.Project.deps_paths/0 is undefined (module Mix.Project is not available)
    Mix.Project.deps_paths()
    (ecto) lib/mix/ecto.ex:172: Mix.Ecto.source_repo_priv/1
    (apartmentex) lib/apartmentex/migrations_path_builder.ex:6: Apartmentex.MigrationsPathBuilder.tenant_migrations_path/1
    (apartmentex) lib/apartmentex/tenant_actions.ex:61: anonymous fn/4 in Apartmentex.TenantActions.migrate_and_return_status/4
    (apartmentex) lib/apartmentex/tenant_actions.ex:72: Apartmentex.TenantActions.handle_database_exceptions/1
    (apartmentex) lib/apartmentex/tenant_actions.ex:57: Apartmentex.TenantActions.migrate_and_return_status/4

**Comment by Dania02525** [comment]
I have just pushed a commit that removes the mix dependency from within the migrations path builder, and uses a similar strategy to the example given in the distillery docs instead.  

[distillery example](https://github.com/bitwalker/distillery/blob/master/docs/Running%20Migrations.md)
[my fix](https://github.com/Dania02525/apartmentex/blob/master/lib/apartmentex/migrations_path_builder.ex)

If you aren't doing so already, please use
```elixir
{:apartmentex, git: "https://github.com/Dania02525/apartmentex.git"}
```
in your deps to get the latest (assuming you aren't on old version of ecto).  

You will need to rebuild with distillery to test this, but it worked for me locally.  Let me know if it works now :-)

**Comment by lulu-2021** [comment]
Thanks for the prompt response - yes that solved the issue - Thanks
